<?php

namespace Database\Seeders;

use App\Models\GroupPackage;
use App\Models\Place;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class GroupPackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $places = Place::all();
        if ($places->isEmpty()) {
            $this->call(PlaceSeeder::class);
            $places = Place::all();
        }

        // Helper function to get place ID
        $getPlaceId = function($slug) use ($places) {
            $place = $places->where('slug', $slug)->first();
            return $place ? $place->id : null;
        };

        $groupPackages = [
            [
                'name' => 'Dubai Group Tour - 20 Pax',
                'slug' => 'dubai-group-tour-20-pax',
                'short_description' => 'Special group package for 20 people exploring Dubai\'s highlights.',
                'description' => '<p>Perfect for large groups! Visit Burj Khalifa, Dubai Mall, Palm Jumeirah, and enjoy a desert safari. Includes group discounts and dedicated guide.</p>',
                'place_id' => $getPlaceId('dubai'),
                'category' => 'Entry Tickets',
                'package_category' => 'Standard',
                'includes_flight' => false,
                'price' => 12000,
                'discount_price' => 10000,
                'price_2_6' => 6000,
                'price_6_10' => 7500,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(7)->format('Y-m-d'),
                'total_pax' => 20,
                'duration' => '1 day',
                'ticket_count' => 1,
                'ticket_name' => 'Group Tour Pass',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Bali Group Honeymoon Package - 15 Couples',
                'slug' => 'bali-group-honeymoon-15-couples',
                'short_description' => 'Group honeymoon package for 15 couples in Bali.',
                'description' => '<p>Special group honeymoon package with luxury resort stay, private beach dinners, spa sessions, and group activities. Perfect for multiple couples traveling together.</p>',
                'place_id' => $getPlaceId('bali'),
                'category' => 'Hotels',
                'package_category' => 'Honeymoon',
                'includes_flight' => true,
                'price' => 75000,
                'discount_price' => 68000,
                'price_2_6' => 38000,
                'price_6_10' => 45000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(12)->format('Y-m-d'),
                'total_pax' => 30,
                'duration' => '5 days, 4 nights',
                'star_rating' => 5,
                'accommodation_type' => 'Luxury Resort',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Singapore Family Group Package - 25 Pax',
                'slug' => 'singapore-family-group-25-pax',
                'short_description' => 'Family-friendly group tour of Singapore attractions.',
                'description' => '<p>Perfect for large families! Visit Universal Studios, Sentosa Island, Gardens by the Bay, and enjoy group meals. Includes family-friendly activities.</p>',
                'place_id' => $getPlaceId('singapore'),
                'category' => 'Entry Tickets',
                'package_category' => 'Standard',
                'includes_flight' => false,
                'price' => 3500,
                'discount_price' => 3000,
                'price_2_6' => 2000,
                'price_6_10' => 2500,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(6)->format('Y-m-d'),
                'total_pax' => 25,
                'duration' => '2 days',
                'ticket_count' => 1,
                'ticket_name' => 'Family Group Pass',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Maldives Group Retreat - 18 Pax',
                'slug' => 'maldives-group-retreat-18-pax',
                'short_description' => 'Exclusive group retreat in overwater villas.',
                'description' => '<p>Luxury group retreat with overwater villa accommodation, all meals included, water sports, spa sessions, and private group activities. Perfect for corporate or family groups.</p>',
                'place_id' => $getPlaceId('maldives'),
                'category' => 'Hotels',
                'package_category' => 'Platinum',
                'includes_flight' => true,
                'price' => 130000,
                'discount_price' => 115000,
                'price_2_6' => 70000,
                'price_6_10' => 85000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(15)->format('Y-m-d'),
                'total_pax' => 18,
                'duration' => '4 days, 3 nights',
                'star_rating' => 5,
                'accommodation_type' => 'Overwater Villa',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Thailand Group Cultural Tour - 30 Pax',
                'slug' => 'thailand-group-cultural-tour-30-pax',
                'short_description' => 'Cultural immersion tour for large groups in Thailand.',
                'description' => '<p>Explore Thai culture with visits to temples, traditional markets, cooking classes, and cultural shows. Includes group transportation and meals.</p>',
                'place_id' => $getPlaceId('thailand'),
                'category' => 'Transport',
                'package_category' => 'Budget',
                'includes_flight' => false,
                'price' => 2800,
                'discount_price' => 2400,
                'price_2_6' => 1500,
                'price_6_10' => 1900,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(4)->format('Y-m-d'),
                'total_pax' => 30,
                'duration' => '1 day',
                'vehicle_type' => 'Air-conditioned Bus',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Malaysia Group Adventure - 22 Pax',
                'slug' => 'malaysia-group-adventure-22-pax',
                'short_description' => 'Adventure activities for groups in Malaysia.',
                'description' => '<p>Thrilling group adventure including Genting Highlands theme park, Batu Caves, KL city tour, and group meals. Perfect for adventure enthusiasts.</p>',
                'place_id' => $getPlaceId('malaysia'),
                'category' => 'Hotels',
                'package_category' => 'Standard',
                'includes_flight' => true,
                'price' => 32000,
                'discount_price' => 28000,
                'price_2_6' => 17000,
                'price_6_10' => 21000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(9)->format('Y-m-d'),
                'total_pax' => 22,
                'duration' => '3 days, 2 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Hotel',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Sri Lanka Group Heritage Tour - 20 Pax',
                'slug' => 'sri-lanka-group-heritage-tour-20-pax',
                'short_description' => 'Heritage sites tour for groups in Sri Lanka.',
                'description' => '<p>Explore UNESCO World Heritage sites including Sigiriya, Anuradhapura, and Kandy. Includes guided tours, accommodation, and group meals.</p>',
                'place_id' => $getPlaceId('sri-lanka'),
                'category' => 'Hotels',
                'package_category' => 'Standard',
                'includes_flight' => true,
                'price' => 42000,
                'discount_price' => 37000,
                'price_2_6' => 21000,
                'price_6_10' => 26000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(11)->format('Y-m-d'),
                'total_pax' => 20,
                'duration' => '5 days, 4 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Boutique Hotel',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Nepal Group Trekking Package - 16 Pax',
                'slug' => 'nepal-group-trekking-16-pax',
                'short_description' => 'Group trekking adventure in the Himalayas.',
                'description' => '<p>Moderate trekking experience with mountain views, village visits, and cultural immersion. Includes guide, porter, accommodation, and meals.</p>',
                'place_id' => $getPlaceId('nepal'),
                'category' => 'Hotels',
                'package_category' => 'Premium',
                'includes_flight' => true,
                'price' => 52000,
                'discount_price' => 46000,
                'price_2_6' => 28000,
                'price_6_10' => 34000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(14)->format('Y-m-d'),
                'total_pax' => 16,
                'duration' => '6 days, 5 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Mountain Lodge',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Goa Group Beach Party - 35 Pax',
                'slug' => 'goa-group-beach-party-35-pax',
                'short_description' => 'Fun beach holiday package for large groups.',
                'description' => '<p>Perfect for groups! Beach activities, water sports, nightlife, and group parties. Includes beachfront accommodation and group meals.</p>',
                'place_id' => $getPlaceId('goa'),
                'category' => 'Hotels',
                'package_category' => 'Budget',
                'includes_flight' => false,
                'price' => 14000,
                'discount_price' => 12000,
                'price_2_6' => 8000,
                'price_6_10' => 10000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(5)->format('Y-m-d'),
                'total_pax' => 35,
                'duration' => '4 days, 3 nights',
                'star_rating' => 3,
                'accommodation_type' => 'Beach Resort',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Kerala Group Backwaters Experience - 24 Pax',
                'slug' => 'kerala-group-backwaters-24-pax',
                'short_description' => 'Group houseboat cruise through Kerala backwaters.',
                'description' => '<p>Experience Kerala\'s famous backwaters on traditional houseboats. Includes village visits, local cuisine, cultural shows, and group activities.</p>',
                'place_id' => $getPlaceId('kerala'),
                'category' => 'Hotels',
                'package_category' => 'Premium',
                'includes_flight' => false,
                'price' => 22000,
                'discount_price' => 19000,
                'price_2_6' => 11000,
                'price_6_10' => 14000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(8)->format('Y-m-d'),
                'total_pax' => 24,
                'duration' => '3 days, 2 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Houseboat',
                'featured' => true,
                'status' => true,
            ],
        ];

        foreach ($groupPackages as $groupPackage) {
            GroupPackage::firstOrCreate(
                ['slug' => $groupPackage['slug']],
                $groupPackage
            );
        }
    }
}
