<?php

namespace Database\Seeders;

use App\Models\Package;
use App\Models\Place;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PackageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $places = Place::all();
        if ($places->isEmpty()) {
            $this->call(PlaceSeeder::class);
            $places = Place::all();
        }

        // Helper function to get place ID
        $getPlaceId = function($slug) use ($places) {
            $place = $places->where('slug', $slug)->first();
            return $place ? $place->id : null;
        };

        $packages = [
            [
                'name' => 'Dubai City Tour with Burj Khalifa',
                'slug' => 'dubai-city-tour-burj-khalifa',
                'short_description' => 'Explore the iconic landmarks of Dubai including Burj Khalifa, Dubai Mall, and Palm Jumeirah.',
                'description' => '<p>Experience the best of Dubai with this comprehensive city tour. Visit the world\'s tallest building Burj Khalifa, shop at Dubai Mall, cruise along Palm Jumeirah, and enjoy traditional Emirati cuisine.</p>',
                'place_id' => $getPlaceId('dubai'),
                'category' => 'Entry Tickets',
                'package_category' => 'Premium',
                'includes_flight' => false,
                'price' => 15000,
                'discount_price' => 12000,
                'price_2_6' => 8000,
                'price_6_10' => 10000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(7)->format('Y-m-d'),
                'total_pax' => 30,
                'duration' => '1 day',
                'ticket_count' => 1,
                'ticket_name' => 'City Tour Pass',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Bali 5 Days 4 Nights Honeymoon Package',
                'slug' => 'bali-5-days-4-nights-honeymoon',
                'short_description' => 'Romantic getaway to Bali with luxury resorts and private tours.',
                'description' => '<p>Perfect honeymoon package in Bali. Stay at luxury beachfront resorts, enjoy private candlelight dinners, visit Ubud rice terraces, and relax at spa retreats.</p>',
                'place_id' => $getPlaceId('bali'),
                'category' => 'Hotels',
                'package_category' => 'Honeymoon',
                'includes_flight' => true,
                'price' => 85000,
                'discount_price' => 75000,
                'price_2_6' => 40000,
                'price_6_10' => 50000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(10)->format('Y-m-d'),
                'total_pax' => 20,
                'duration' => '5 days, 4 nights',
                'star_rating' => 5,
                'accommodation_type' => 'Luxury Resort',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Singapore Universal Studios Entry',
                'slug' => 'singapore-universal-studios',
                'short_description' => 'Full day access to Universal Studios Singapore theme park.',
                'description' => '<p>Enjoy a full day at Universal Studios Singapore with access to all rides, shows, and attractions. Includes express pass for popular rides.</p>',
                'place_id' => $getPlaceId('singapore'),
                'category' => 'Entry Tickets',
                'package_category' => 'Standard',
                'includes_flight' => false,
                'price' => 4500,
                'discount_price' => 3800,
                'price_2_6' => 2500,
                'price_6_10' => 3200,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(5)->format('Y-m-d'),
                'total_pax' => 50,
                'duration' => '1 day',
                'ticket_count' => 1,
                'ticket_name' => 'Universal Studios Day Pass',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Maldives Water Villa Stay',
                'slug' => 'maldives-water-villa-stay',
                'short_description' => 'Luxury overwater villa experience in the Maldives.',
                'description' => '<p>Stay in a stunning overwater villa with direct access to the crystal-clear lagoon. Includes all meals, water sports, and spa treatments.</p>',
                'place_id' => $getPlaceId('maldives'),
                'category' => 'Hotels',
                'package_category' => 'Platinum',
                'includes_flight' => true,
                'price' => 150000,
                'discount_price' => 130000,
                'price_2_6' => 75000,
                'price_6_10' => 90000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(14)->format('Y-m-d'),
                'total_pax' => 15,
                'duration' => '4 days, 3 nights',
                'star_rating' => 5,
                'accommodation_type' => 'Overwater Villa',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Thailand Bangkok City Tour',
                'slug' => 'thailand-bangkok-city-tour',
                'short_description' => 'Explore the vibrant city of Bangkok with temple visits and river cruise.',
                'description' => '<p>Discover Bangkok\'s rich culture with visits to Grand Palace, Wat Pho, and a Chao Phraya River cruise. Includes traditional Thai lunch.</p>',
                'place_id' => $getPlaceId('thailand'),
                'category' => 'Transport',
                'package_category' => 'Budget',
                'includes_flight' => false,
                'price' => 3500,
                'discount_price' => 3000,
                'price_2_6' => 2000,
                'price_6_10' => 2500,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(3)->format('Y-m-d'),
                'total_pax' => 40,
                'duration' => '1 day',
                'vehicle_type' => 'Air-conditioned Bus',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Malaysia Kuala Lumpur & Genting Highlands',
                'slug' => 'malaysia-kl-genting',
                'short_description' => 'Explore KL city and enjoy Genting Highlands theme park.',
                'description' => '<p>Visit Petronas Twin Towers, Batu Caves, and spend a day at Genting Highlands theme park with hotel stay included.</p>',
                'place_id' => $getPlaceId('malaysia'),
                'category' => 'Hotels',
                'package_category' => 'Standard',
                'includes_flight' => true,
                'price' => 35000,
                'discount_price' => 30000,
                'price_2_6' => 18000,
                'price_6_10' => 22000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(8)->format('Y-m-d'),
                'total_pax' => 25,
                'duration' => '3 days, 2 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Hotel',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Sri Lanka Cultural Triangle Tour',
                'slug' => 'sri-lanka-cultural-triangle',
                'short_description' => 'Explore ancient cities and UNESCO World Heritage sites.',
                'description' => '<p>Visit Sigiriya Rock Fortress, ancient city of Anuradhapura, and the Temple of the Tooth in Kandy. Includes guided tours and accommodation.</p>',
                'place_id' => $getPlaceId('sri-lanka'),
                'category' => 'Hotels',
                'package_category' => 'Standard',
                'includes_flight' => true,
                'price' => 45000,
                'discount_price' => 40000,
                'price_2_6' => 22000,
                'price_6_10' => 28000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(12)->format('Y-m-d'),
                'total_pax' => 20,
                'duration' => '5 days, 4 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Boutique Hotel',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Nepal Kathmandu & Pokhara Adventure',
                'slug' => 'nepal-kathmandu-pokhara',
                'short_description' => 'Mountain views and adventure activities in Nepal.',
                'description' => '<p>Explore Kathmandu\'s temples, fly to Pokhara for mountain views, and enjoy paragliding. Includes all transfers and accommodation.</p>',
                'place_id' => $getPlaceId('nepal'),
                'category' => 'Hotels',
                'package_category' => 'Premium',
                'includes_flight' => true,
                'price' => 55000,
                'discount_price' => 48000,
                'price_2_6' => 28000,
                'price_6_10' => 35000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(15)->format('Y-m-d'),
                'total_pax' => 18,
                'duration' => '6 days, 5 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Mountain Resort',
                'featured' => true,
                'status' => true,
            ],
            [
                'name' => 'Goa Beach Holiday Package',
                'slug' => 'goa-beach-holiday',
                'short_description' => 'Relax on pristine beaches and enjoy water sports.',
                'description' => '<p>Stay at a beachfront resort in Goa. Enjoy water sports, visit spice plantations, and experience vibrant nightlife. All meals included.</p>',
                'place_id' => $getPlaceId('goa'),
                'category' => 'Hotels',
                'package_category' => 'Budget',
                'includes_flight' => false,
                'price' => 18000,
                'discount_price' => 15000,
                'price_2_6' => 9000,
                'price_6_10' => 11000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(6)->format('Y-m-d'),
                'total_pax' => 35,
                'duration' => '4 days, 3 nights',
                'star_rating' => 3,
                'accommodation_type' => 'Beach Resort',
                'featured' => false,
                'status' => true,
            ],
            [
                'name' => 'Kerala Backwaters Houseboat Cruise',
                'slug' => 'kerala-backwaters-houseboat',
                'short_description' => 'Experience Kerala\'s famous backwaters on a traditional houseboat.',
                'description' => '<p>Stay overnight on a traditional Kerala houseboat, cruise through backwaters, enjoy local cuisine, and visit tea plantations in Munnar.</p>',
                'place_id' => $getPlaceId('kerala'),
                'category' => 'Hotels',
                'package_category' => 'Premium',
                'includes_flight' => false,
                'price' => 25000,
                'discount_price' => 22000,
                'price_2_6' => 12000,
                'price_6_10' => 15000,
                'currency' => 'INR',
                'announcement_date' => now()->addDays(9)->format('Y-m-d'),
                'total_pax' => 25,
                'duration' => '3 days, 2 nights',
                'star_rating' => 4,
                'accommodation_type' => 'Houseboat',
                'featured' => true,
                'status' => true,
            ],
        ];

        foreach ($packages as $package) {
            Package::firstOrCreate(
                ['slug' => $package['slug']],
                $package
            );
        }
    }
}
